version: '3.8'

services:
  django_service:
    restart: always
    build: .
    container_name: django
    ports:
      - "8000:8000"
    environment:
      DEBUG: "true"
      ES_HOST: elasticsearch_service
      ES_PORT: 9200
#      DB_ENGINE: django.db.backends.mysql
#      DB_NAME: p8_mysql_group_db
#      DB_USER: root
#      DB_PASSWORD: 1
#      DB_HOST: mysql_service
#      DB_PORT: 3306

    depends_on:
      - elasticsearch_service
#      - mysql_service
#      - redis_service
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"

#  postgres_service: ✅
#    restart: always
#    image: postgres:alpine
#    container_name: p8_pg_db
#    environment:
#      POSTGRES_DB: p8_postgres_group_db
#      POSTGRES_PASSWORD: 1
#    ports:
#      - "5432:5432"
#    volumes:
#      - pg_data:/var/lib/postgresql/data/

#  mysql_service: ✅
#    restart: always
#    image: mysql
#    container_name: p8_mysql_db
#    ports:
#        - "3306:3306"
#    environment:
#        MYSQL_DATABASE: p8_mysql_group_db
#        MYSQL_ROOT_PASSWORD: 1
#    volumes:
#      - my_data:/var/lib/mysql

#  redis_service: ✅
#    restart: always
#    image: redis:alpine
#    container_name: p8_redis_cache
#    ports:
#        - "6379:6379"
#    volumes:
#      - redis_data:/data

  elasticsearch_service:
    restart: always
    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.0
    container_name: p8_elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
    volumes:
      - els_data:/usr/share/elasticsearch/data

volumes:
#  pg_data:
#  my_data:
#  redis_data:
  els_data:
