# Generated by Django 4.2 on 2023-04-20 06:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('details', models.TextField()),
                ('years_ago', models.PositiveIntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Car',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
