# Generated by Django 4.2 on 2023-04-13 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
