# Generated by Django 4.2 on 2023-04-13 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_product_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to='products/%Y/%m/%d'),
        ),
    ]
